const categories=["Alle","Vergebung","Schutz","Familie","Wissen","Versorgung","Wohlbefinden","Geduld","Alltag"];
const $=s=>document.querySelector(s);
let selected="Alle",onlyFav=false;
const loadFav=()=>{try{return JSON.parse(localStorage.getItem("dua-favorites")||"[]")}catch{return []}};
let favorites=loadFav();
function saveFav(){try{localStorage.setItem("dua-favorites",JSON.stringify(favorites))}catch{}}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function drawFilters(){$("#filters").innerHTML=categories.map(c=>`<button class="${c===selected?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join("");$("#filters").querySelectorAll("button").forEach(b=>b.onclick=()=>{selected=b.dataset.cat;drawFilters();render()})}
function render(){const q=$("#search").value.trim().toLocaleLowerCase("de");const items=DUAS.filter(d=>(selected==="Alle"||d.category===selected)&&(!onlyFav||favorites.includes(d.id))&&(d.title+" "+d.category+" "+d.de+" "+d.latin+" "+d.ar).toLocaleLowerCase("de").includes(q));$("#listtitle").textContent=onlyFav?"Meine Favoriten":"Bittgebete";$("#favCount").textContent=favorites.length;
if(!items.length){$("#results").innerHTML='<div class="empty">Keine passenden Einträge gefunden. Ändere die Suche oder speichere Favoriten.</div>';return}
$("#results").innerHTML=items.map(d=>`<article class="card"><div class="cardhead"><div><div class="tag">${esc(d.category)} · ${esc(d.kind)}</div><h3>${esc(d.title)}</h3></div><button class="smallbtn" data-fav="${d.id}" aria-label="Favorit umschalten">${favorites.includes(d.id)?"♥":"♡"}</button></div><div class="arabic" lang="ar" dir="rtl">${d.ar}</div><div class="label">LAUTSCHRIFT</div><div class="latin">${esc(d.latin)}</div><div class="label">DEUTSCHE BEDEUTUNG</div><div class="meaning">${esc(d.de)}</div><div class="source">Quelle: ${esc(d.source)}</div><div class="actions"><button data-speak="${d.id}">🔊 Anhören</button><button data-copy="${d.id}">Text kopieren</button></div></article>`).join("");
$("#results").querySelectorAll("[data-fav]").forEach(b=>b.onclick=()=>{const id=Number(b.dataset.fav);favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];saveFav();render()});
$("#results").querySelectorAll("[data-copy]").forEach(b=>b.onclick=async()=>{const d=DUAS.find(x=>x.id===Number(b.dataset.copy));const text=`${d.ar}\n${d.latin}\n${d.de}\nQuelle: ${d.source}`;try{await navigator.clipboard.writeText(text);b.textContent="✓ Kopiert"}catch{window.prompt("Text kopieren:",text)}});
$("#results").querySelectorAll("[data-speak]").forEach(b=>b.onclick=()=>{const d=DUAS.find(x=>x.id===Number(b.dataset.speak));if(!("speechSynthesis" in window)){alert("Die Audioausgabe wird von diesem Browser nicht unterstützt.");return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(d.ar);u.lang="ar-SA";u.rate=.78;const voices=speechSynthesis.getVoices();const arVoice=voices.find(v=>v.lang.toLowerCase().startsWith("ar"));if(arVoice)u.voice=arVoice;speechSynthesis.speak(u);b.textContent="▶ Wird abgespielt…";u.onend=()=>b.textContent="🔊 Anhören";u.onerror=()=>b.textContent="🔊 Erneut versuchen"})}
$("#search").addEventListener("input",render);$("#favToggle").onclick=()=>{onlyFav=!onlyFav;$("#favToggle").firstChild.textContent=onlyFav?"Alle anzeigen ":"♡ Favoriten (";render()};
drawFilters();render();
if("serviceWorker" in navigator && location.protocol.startsWith("http"))window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));